name: Release (Ubuntu)

on:
  workflow_dispatch:

jobs:
  release-ubuntu:
    # Always build on the oldest linux version we want to support
    # See https://pyinstaller.readthedocs.io/en/stable/usage.html#making-gnu-linux-apps-forward-compatible
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install production dependencies
        run: poetry install --no-dev

      - name: Install UPX
        run: brew install upx

      - name: Bundle executable
        run: poetry run pyinstaller -F bundle/bundle.spec

      - name: Show directory content
        run: |
          cd dist
          ls -l
